final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
import website.views
from website.models import *


from django_otp.admin import OTPAdminSite
from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin
from django_mptt_admin.admin import DjangoMpttAdmin


class ProjectAdmin(DjangoMpttAdmin):
    pass

class OTPAdmin(OTPAdminSite):
    pass


admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)
admin_site.register(Furniture)
admin_site.register(Vehicle_identification)
admin_site.register(Furniture_pictures)
admin_site.register(Furniture_likes)
admin_site.register(Vehicle_likes)
admin_site.register(Message)
admin_site.register(Vehicle_pictures)
admin_site.register(Profile)
admin_site.register(Project, ProjectAdmin)
admin_site.register(Comment)











urlpatterns = [
    path('901252112/', admin_site.urls),
    path('', include('website.urls')),
    #path('tinymce/', include('tinymce.urls')),
    #url(r'^messages/', include('postman.urls', namespace='postman')),
    url('^', include('django.contrib.auth.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name = 'website'

urlpatterns = [
    path('genres/', views.show_genres),
    path('profile/<user>', views.ProfileMessageView.as_view(), name='profile'),
    path('editprofile/<user>', views.ProfileEditView.as_view(), name='editprofile'),
    path('vehicledeleterequest/<slug>', views.VehicleDeleteView.as_view(), name='deletevehicle'),
    path('furnituredeleterequest/<pk>', views.FurnitureDeleteView.as_view(), name='deletefurniture'),
    path('accountdeleterequest/<user>', views.AccountDeleteView.as_view(), name='deleteaccount'),
    path('furniture/<slug>', views.ListFurnitureView.as_view(), name='list_furniture'),
    path('furnish/<slug>', views.FurnitureCreate.as_view(), name="furnish"),
    path('', views.index, name='index'),
    path('addvehicle/', views.VehicleCreate.as_view(), name='addvehicle'),
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('garage/<user>', views.GarageView.as_view(), name='garage'),
    path('editfurniture/<pk>', views.FurnitureEdit.as_view(), name='editfurniture'),
    path('editvehicle/<slug>', views.VehicleEdit.as_view(), name='editvehicle'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('furniturebytechnique/<technique>', views.FurniturebyTechnique.as_view(), name='listfurniturebytechnique'),
    path('furniturebybuilder/<builder>', views.FurniturebyBuilder.as_view(), name='furniturebybuilder'),
    path('vehicle/<slug>', views.VehicleView.as_view(), name='vehicle'),
    path('like', views.like, name='like'),
    path('deletemessage', views.deletemessage, name='deletemessage'),
    #path('projectpreview', views.projectpreview, name="projectpreview"),
    path('furniturebytype/<type>', views.FurniturebyType.as_view(), name='furniturebytype'),
    path('searchvehicles', views.VehicleSearch.as_view(), name='searchvehicles'),
    path('vehlike', views.vehlike, name='vehlike'),
    path('comment/reply/', views.reply_page, name="reply")

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/views.py
# Credits: "Ordinarycoders.com" for tutorial on using Django's userauthenticationsystem (see register, login_request, logout functions)

from django.contrib.auth.models import Permission
from django.core.exceptions import PermissionDenied
from django.forms.models import modelform_factory
from django.views.generic.base import RedirectView
from multiselectfield.db.fields import add_metaclass
from website.models import Furniture_pictures, Vehicle_identification, Furniture, Vehicle_pictures
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from .forms import *
from .models import *
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import SingleObjectMixin
from django.forms.models import inlineformset_factory
from django.db import transaction
from django import forms
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from website.tokens import account_activation_token
from django.utils.encoding import force_text, force_bytes
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
import json
from django.views import View
from django.views.generic.detail import DetailView, BaseDetailView
from django.utils.text import slugify
from .utils import url_tag, image_path, number_extractor
from django.db.models import Q





def show_genres(request):
    return render(request, "website/projects.html", {'projects': Project.objects.all()})


def index(request):
    return render(request, "base.html", {'projects': Project.objects.all()})

# credit https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
def register(request):
    if request.method == "POST":
        user_form = NewUserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active=False
            user.save()
            user.refresh_from_db()
            profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
            profile_form.full_clean()
            image =  profile_form.cleaned_data['profile_pic']
            profile_form.save()
            current_site = get_current_site(request)
            subject = 'Please activate your Tiny Shelter Archives Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            messages.info(request, "We sent an email to your email account. Please confirm account to finish registration.")
            return redirect('website:index')
        messages.error(request, "Unsuccessful registration. Invalid information.")
    else:
        user_form = NewUserForm()
        profile_form = ProfileForm()
    return render(request, "register.html", {
        "user_form":user_form,
        "profile_form": profile_form,
        'projects': Project.objects.all()
        })

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        messages.info(request, "Thanks for joining the site!")

        return redirect('website:index')
    else:
        messages.error(request, "Unsuccessful registration. Invalid activation.")
        return redirect('website:index')

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'Currently logged in as {username}')
                return redirect('website:index')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, 'login.html', {"form": form, 'projects': Project.objects.all()})

def logout_request(request):
    logout(request)
    messages.info(request, "Currently logged out")
    return redirect("website:index")

class AccountDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'login'
    model = Furniture
    success_message = "Successfully deleted account."
    template_name = "website/delete_confirmation.html"
    slug_for_redirect = None

    def get_queryset(self):
        qs = super(AccountDeleteView, self).get_queryset()
        return qs.filter(owner=self.request.user)

    def get_object(self):
        user = self.kwargs.get('user')
        if user == self.request.user.username:
            return Profile.objects.get(user=self.request.user)
        else:
            raise PermissionDenied


    def get_context_data(self, **kwargs):
        data = super(AccountDeleteView, self).get_context_data(**kwargs)
        data['projects'] = Project.objects.all()
        return data

    def get_success_url(self, **kwargs):
        user = self.request.user
        user.delete()
        messages.info(self.request, "Your account was deleted :(")
        return reverse('website:index')

class ProfileView(LoginRequiredMixin, DetailView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    template_name= 'profile.html'
    model = User
    context_object_name = 'contributor'

    def get_object(self, **kwargs):
        user_object = User.objects.get(username=self.kwargs.get('user'))
        return user_object

    def get_sent_emails(self):
        if self.request.user != self.get_object():
            return None
        return Message.objects.filter(sender=self.request.user)   
    
    def get_recieved_emails(self):
        if self.request.user != self.get_object():
            return None
        return Message.objects.filter(recipient=self.request.user)
          
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sent_emails'] = self.get_sent_emails()
        context['recieved_emails'] = self.get_recieved_emails()
        context['form']=MessageForm()
        context['projects']=Project.objects.all()
        return context

class MessageView(SingleObjectMixin, FormView):
    def get_object(self, **kwargs):
        user_object = User.objects.get(username=self.kwargs.get('user'))
        return user_object

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object = self.get_object()
        form = MessageForm(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender = self.request.user
        message.recipient = User.objects.get(username=self.kwargs.get('user'))
        message.save()
        messages.info(self.request, "Email sent.")
        return HttpResponseRedirect(reverse_lazy('website:profile', kwargs={'user': self.kwargs.get('user')}))



class ProfileMessageView(View):
    def get(self, request, *args, **kwargs):
        view = ProfileView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = MessageView.as_view()
        return view(request, *args, **kwargs)

class ProfileEditView(LoginRequiredMixin, UpdateView):
    login_url = 'website/login'
    redirect_field_name = 'redirect_to'
    model = Profile
    template_name = 'editprofile.html'
    form_class= ProfileForm
    success_url = None
    def get_object(self):
        user = self.kwargs.get('user')
        if user == self.request.user.username:
            return Profile.objects.get(user=self.request.user)
        else:
            raise PermissionDenied


    def get_context_data(self, **kwargs):
        context = super(ProfileEditView, self).get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context

    def get_success_url(self):
        return reverse('website:profile', kwargs={'user': self.request.user.username}, )

class GarageView(ListView):
    template_name = 'website/garage.html'

    model = Vehicle_pictures
    
    #def get_queryset(self):
     #   return Vehicle_pictures.objects.filter(parent__owner=self.request.user)

    def number_of_likes(self):
        garage_owner = self.kwargs.get('user')
        owner = User.objects.get(username=garage_owner)
        list = Vehicle_identification.objects.filter(owner=owner)
        number_of_likes_dictionary = {}
        for item in list:

website/templates/website/add_vehicle.html
{% extends 'base.html' %}


<!--
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="en">
<head>
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   
    <title>
     
    </title>
</head>
<body>
-->
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10">
    <!--removed novalidate-->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'website/formhelper.html' with form=addvehicleForm %}
        <table class="table">
            {{ formset.management_form }}
            {% for form in formset.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %} 
            
            <tr class="formset_row">
              {% for field in form.visible_fields %}
                  <td>
                      {# Include the hidden fields in the form #}
                      {% if forloop.first %}
                          {% for hidden in form.hidden_fields %}
                              {{ hidden }}
                          {% endfor %}
                      {% endif %}
                      {{ field.errors.as_ul }}
                      {{ field }}
                      {% if form.instance.pk %}
                      {{form.DELETE}}
                      {% endif %}
      
                
                  </td>
              {% endfor %}
          </tr>
          {% endfor %}
        </table>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
        </div>
    </div>

    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'Add more images',
            deleteText: 'remove',
            prefix: 'familymember_set'
        });
      </script>
{% endblock content %}

website/templates/website/comments.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>Commenter: {{comment.name}}</strong> 
        {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
    </div>
    <div class="border p-2 rounded">
            <p>{{comment.body}}</p>
        {% if comment.image %}
        <img src='{{comment.image.url}}' class='comment_image'>
        {% endif %}
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>

        <div id="reply-form-container-{{comment.id}}" style="display: none;">  
        
            <form method="post" action="{% url 'website:reply' %}" class="mt-3" enctype="multipart/form-data">
                
                {% csrf_token %}
                <input type="hidden" name="vehicle_id" value="{{object.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="current_url" value="{{ request.build_absolute_uri}}">

                {{comment_form.as_p}}
                <div>
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <div class='ml-4'>
    {% for comment in comment.get_comments %}
        {% include 'website/comments.html' with comment=comment %}
    {% endfor %}
    </div>
</div>

website/templates/website/delete_confirmation.html
{% extends 'base.html' %}

{% load custom_tags %} 


{% block content %}

<div class='content'>
<b>Confirm deletion of this entry?</b>
<br>

<br>
<div style='max-width: fit-content; margin-left:40px'>
    {% with object|classname as type %}
    {% if type == "Vehicle_identification" %}
    <h6 class="text-center text-muted">{{object.name}}</h6>


    {% elif type == "Furniture" %}

    <h6 class="text-center text-muted">Titled: {{object.room}} - located in {{object.vehicle.name}}</h6>


    {% endif %}
    {% endwith %}





    <br>
        <form method="post">{% csrf_token %}
        <input class="btn-primary btn-lg btn-block" type="submit" value="Confirm">
        <br>
        </form>

        {% with object|classname as type %}
            {% if type == "Vehicle_identification" %}
            
            <a class="btn-secondary btn-lg btn-block text-center" style='color:white;margin-left:0px' href="{% url 'website:garage' user.username %}" role="button">Cancel</a>    

            {% elif type == "Furniture" %}

            <a class="btn-secondary btn-lg btn-block text-center" style='color:white;margin-left:0px' href="{% url 'website:list_furniture' object.vehicle.slug %}" role="button">Cancel</a>    


            {% endif %}
            {% endwith %}

</div>

</div>

{% endblock content %}

website/templates/website/furniture_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content">

            <h5>Build it out</h5>
   
             {% crispy form %}
  
</div>
{% endblock content %}

website/templates/website/garage.html
{% extends 'base.html' %}
{% load custom_tags %} 



{% block header %} 

Garage

{% endblock header %} 



{% block content %}

<div class="content">
    <h5 class='text-muted'>Vehicles</h5>   


    {% if user.is_authenticated and user.username == garage_owner %}
    <div span='in-block'>
      
        <a style='font-size:1em' href="{% url 'website:addvehicle' %}">Add a vehicle</a>
    </div>
    {% endif %}
    
    <div class="garage-flex">

        {% if not vehicle_list %}

        Nothing here yet
    
        {% endif %}


    {% for ride in vehicle_list %} 
    
   


        <div class='search-results'>
            <div class='search-results-child'>
            <span><b>Vehicle name:</b></span>
            <p class='indent' > <a href="{% url 'website:vehicle' ride.slug %}">{{ride.name}}</a></p>
            <span><b>Vehicle base:</b></span>
            <p class='indent' >{{ride.project_base}}</p>
            <span><b>Predominant build technique:</b></span>
            <p class='indent'>{{ride.build_techniques}}</p>
            <span><b>Builder profile: </b></span>
            <a href="{% url 'website:profile' ride.owner %}">{{ride.owner}}</a>
            <br>
            <br>
            <span>

                <button type="button" onclick=vehlike({{ride.pk}}) class="btn btn-default like" aria-label="Left Align">
                    <i class="fas fa-thumbs-up"></i>
                </button>
                <span class="mt-2" id="{{ride.pk}}"> {{like_ref|get_item:ride.pk}}</span>          
                <span class='small ml-0' id={{ride.pk}}-label></span>


            </span>
        
            </div>
        
            <div class='search-results-child'>
                <span><b>Description:</b></span>
                <p style='overflow-wrap: break-word;' class='indent'>{{ride.vehicle_description |safe}}</p>
            
            
            <a href="{% url 'website:vehicle' ride.slug %}">Go to build page</a>
            <br>

            {% if user == ride.owner %}
            <a href="{% url 'website:furnish' ride.slug %}">Add furniture to your vehicle</a>
            <br>
            <a  href="{% url 'website:editvehicle' ride.slug %}">   Edit your vehicle</a>
            <br>
            <a href="{% url 'website:deletevehicle' ride.slug %}">   Delete your vehicle</a>
            
            {% endif %}
            
            </div>
            


            <div class='search-results-child garage-pic-section'>
                <div class="search-results-child-pictures">
                    <span sytle='font-size:10px'>Exterior pictures</span>
                    {% for image in ride.images.all %} 
                    {% if forloop.first %}                
                    <a href="{{image.image.url}}" data-toggle="lightbox" data-gallery="{{ride}}" class="lightboximg" data-footer="{{image.annotation}}">
                    <img src="{{image.image.url}}" class="img-fluid">
                    </a>
                    {% else %}
                    <div data-toggle="lightbox" data-gallery="{{ride}}" data-remote="{{image.image.url}}" data-footer="{{image.annotation}}"></div>

                    {% endif %}

                     {% endfor %}
                </div>

                <div class="search-results-child-pictures">
                    <span sytle='font-size:10px'>Interior pictures</span>
                    {% for image in furniture_image_list|get_images:ride.pk %} 

                    {% if not image %}
                    Nothing built in here yet
                    {% endif %}

                    {% if forloop.first %}                
                    <a href="{{image.image.url}}" data-toggle="lightbox" data-gallery="{{ride}}-interior" class="lightboximg" data-footer="{{image.annotation}}">
                    <img src="{{image.image.url}}" class="img-fluid">
                    </a>
                    {% else %}
                    <div data-toggle="lightbox" data-gallery="{{ride}}-interior" data-remote="{{image.image.url}}" data-footer="{{image.annotation}}"></div>

                    {% endif %}

                     {% endfor %}
                </div>




            </div>












            </div>
        
        
        


     
                
  {% endfor %}

</div>
</div>


{% endblock content %}

website/templates/website/projects.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load custom_tags %} {%
load static %} {% load mptt_tags %} {% block content %}

<article class="content">
  <h3><span class="text-muted">Build page:</span> {{object.name}}</h3>

  <br />

  <span><i class="fas fa-scroll"></i> Basic stats</span>

  <div class="stats">
    <div>
      <span><b>Vehicle base:</b></span>
      <p class="indent">{{object.project_base}}</p>
      <span><b>Predominant build technique:</b></span>
      <p class="indent">{{object.build_techniques}}</p>
      <span><b>Builder profile: </b></span>
      <a href="{% url 'website:profile' object.owner %}">{{object.owner}}</a>
      <br />
      <br />
      <span>
        <span>Views: {{object.view_count}}</span>
        <br />
        <button
          type="button"
          onclick="vehlike({{object.pk}})"
          class="btn btn-default like"
          aria-label="Left Align"
        >
          <i class="fas fa-thumbs-up"></i>
        </button>
        <span class="mt-2" id="{{object.pk}}">
          {{like_ref|get_item:object.pk}}</span
        >
        <span class="small ml-0" id="{{object.pk}}-label"></span>
      </span>
    </div>
    <div style="margin-right: 33%">
      <span><b>Description:</b></span>
      <p class="indent">{{object.vehicle_description |safe}}</p>

      {% if user == object.owner %}
      <a href="{% url 'website:furnish' object.slug %}">
        Add furniture to your vehicle</a
      >
      <br />
      <a href="{% url 'website:editvehicle' object.slug %}">
        Edit your vehicle</a
      >
      <br />
      <a href="{% url 'website:deletevehicle' object.slug %}">
        Delete your vehicle</a
      >

      {% endif %}
    </div>
  </div>

  <br />

  <span class="titles">Exterior pictures</span>

  <button class="dropdown0">
    <img src="/static/down.png" class="dropdown-img0" />
  </button>
  <br />
  <br />
  <div class="picture-section0">
    {% for image in image_list %} {% if forloop.first %}
    <a
      href="{{image.image.url}}"
      data-toggle="lightbox"
      data-gallery="{{object.id}}"
      class=""
      data-footer="{{image.annotation}}"
    >
      <span>Pop-up slideshow</span>
    </a>
    {% else %}
    <div
      data-toggle="lightbox"
      data-gallery="{{object.id}}"
      data-remote="{{image.image.url}}"
      data-footer="{{image.annotation}}"
    ></div>

    {% endif %} {% endfor %}
    <div class="carousel">
      <button class="carousel__button carousel__button--left">
        <img src="/static/PREV.png" />
      </button>
      <div class="carousel__track">
        {% for image in image_list %} {% if forloop.first %}

        <img
          class="carousel__image show"
          src="{{image.image.url}}"
          alt="{{image.annotation}}"
        />

        {% else %}

        <img
          class="carousel__image"
          src="{{image.image.url}}"
          alt="{{image.annotation}}"
        />

        {% endif %} {% endfor %}
      </div>
      <button class="carousel__button carousel__button--right">
        <img src="/static/NEXT.png" />
      </button>

      <div class="carousel-caption">
        <p id="image_annotation">{{image_list.0.annotation}}</p>
      </div>
    </div>
  </div>

  {{furniture.list.0.images.0.annotation}} 
  {% regroup furniture by room as f_list %}
   {% for furniture in f_list %} 
   {% with outer_counter=forloop.counter%} 
   {% if forloop.first %}

  <div id="group_count" style="display: none">{{f_list|length}}</div>

  {% endif%}

  <span class="titles">{{furniture.grouper}}</span>

  <button style="display: inline-block" ; class="dropdown{{outer_counter}}">
    <img src="/static/down.png" class="dropdown-img{{outer_counter}}" />
  </button>
  <br />
  <br />
  <div class="picture-section{{outer_counter}}">
    {% for image in furniture.list.0.images.all %} 
    {% if forloop.first %}
    <a
      href="{{image.image.url}}"
      data-toggle="lightbox"
      data-gallery="{{furniture.grouper}}"
      class=""
      data-footer="{{image.annotation}}"
    >
      <span>Pop-up slideshow</span>
    </a>
    {% else %}
    <div
      data-toggle="lightbox"
      data-gallery="{{furniture.grouper}}"
      data-remote="{{image.image.url}}"
      data-footer="{{image.annotation}}"
    ></div>

    {% endif %} 
    {% endfor %}

    <div style="margin-left: 5%">
      {% if user == furniture.list.0.builder %}
      <div class="float-right" style="margin-right: 10%">
        <span>
          <a href="{% url 'website:editfurniture' furniture.list.0.id %}"
            >Edit</a
          >
          <a href="{% url 'website:deletefurniture' furniture.list.0.pk %}"
            >Delete</a
          >
        </span>
      </div>
      {% endif %}

      <span><b>Predominant functionality: </b></span
      ><span>{{furniture.list.0.functionality}}</span>
      <br />
      <span> Posted: {{ furniture.list.0.timestamp |date:"M Y" }} </span>
      <br />
      <span><b>Description: </b></span>
      <p id="description">{{furniture.list.0.description|safe}}</p>
    </div>

    <div class="carousel">
      <button
        class="carousel__button{{outer_counter}} carousel__button--left{{outer_counter}}"
      >
        <img src="/static/PREV.png" />
      </button>
      <div class="carousel__track{{outer_counter}}">
        {% for image in furniture.list.0.images.all %} 
        {% if forloop.first %}

        <img
          class="carousel__image show{{outer_counter}}"
          src="{{image.image.url}}"
          alt="{{image.annotation}}"
        />

        {% else %}

        <img
          class="carousel__image"
          src="{{image.image.url}}"
          alt="{{image.annotation}}"
        />

        {% endif %} {% endfor %}
      </div>
      <button
        class="carousel__button{{outer_counter}} carousel__button--right{{outer_counter}}"
      >
        <img src="/static/NEXT.png" />
      </button>

      <div class="carousel-caption">
        <p id="image_annotation{{outer_counter}}">
          {{furniture.list.0.images.0.annotation}}
        </p>
      </div>
    </div>
  </div>

  {% endwith %} 
  {% endfor %}

  <br />
  <hr />
  <h5 style="font-family: Homemade Apple, sans-serif">Add a comment</h5>
  <!-- <div class="holder clip">
    <div class="circle circle1"></div>
    <div class="circle circle2"></div>
</div> -->

  <div id="scrollable_comments">
    <!-- <h5>Add a comment</h5> -->

    <div
      class="ml-5"
      style="
        background-color: rgba(255, 245, 216, 0.518);
        border-radius: 1em;
        padding: 1em;
        max-width: 100%;
      "
    >
      <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ comment_form.as_p }}

        <button type="submit" class="btn btn-primary btn-sm">New post</button>
      </form>
    </div>
    <br />
    {% with comments.count as total_comments %}
    <span class="mt-5 titles">
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </span>
    {% endwith %} 
    {% if not object.comments.all %}
     No comments yet 
     {% else %} 
     {% for comment in object.get_comments %} 
     {% include 'website/comments.html' with comment=comment %} 
     {% endfor %} 
     {% endif %}
  </div>
</article>

{% endblock content %}

website/templates/website/vehicle_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{form_media}}

<div class="content">
        <h5> Project creation form</h5>
        {% csrf_token %}


        {% crispy form %}
        
   
</div>
{% endblock content %} 