final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
import website.views
from website.models import *


from django_otp.admin import OTPAdminSite
from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin
from django_mptt_admin.admin import DjangoMpttAdmin


class ProjectAdmin(DjangoMpttAdmin):
    pass

class OTPAdmin(OTPAdminSite):
    pass


admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)
admin_site.register(Furniture)
admin_site.register(Vehicle_identification)
admin_site.register(Furniture_pictures)
admin_site.register(Furniture_likes)
admin_site.register(Vehicle_likes)
admin_site.register(Message)
admin_site.register(Vehicle_pictures)
admin_site.register(Profile)
admin_site.register(Project, ProjectAdmin)
admin_site.register(Comment)











urlpatterns = [
    path('901252112/', admin_site.urls),
    path('', include('website.urls')),
    #path('tinymce/', include('tinymce.urls')),
    #url(r'^messages/', include('postman.urls', namespace='postman')),
    url('^', include('django.contrib.auth.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name = 'website'

urlpatterns = [
    path('genres/', views.show_genres),
    path('profile/<user>', views.ProfileMessageView.as_view(), name='profile'),
    path('editprofile/<user>', views.ProfileEditView.as_view(), name='editprofile'),
    path('vehicledeleterequest/<slug>', views.VehicleDeleteView.as_view(), name='deletevehicle'),
    path('furnituredeleterequest/<pk>', views.FurnitureDeleteView.as_view(), name='deletefurniture'),
    path('accountdeleterequest/<user>', views.AccountDeleteView.as_view(), name='deleteaccount'),
    path('furniture/<slug>', views.ListFurnitureView.as_view(), name='list_furniture'),
    path('furnish/<slug>', views.FurnitureCreate.as_view(), name="furnish"),
    path('', views.index, name='index'),
    path('addvehicle/', views.VehicleCreate.as_view(), name='addvehicle'),
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('garage/<user>', views.GarageView.as_view(), name='garage'),
    path('editfurniture/<pk>', views.FurnitureEdit.as_view(), name='editfurniture'),
    path('editvehicle/<slug>', views.VehicleEdit.as_view(), name='editvehicle'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('furniturebytechnique/<technique>', views.FurniturebyTechnique.as_view(), name='listfurniturebytechnique'),
    path('furniturebybuilder/<builder>', views.FurniturebyBuilder.as_view(), name='furniturebybuilder'),
    path('vehicle/<slug>', views.VehicleView.as_view(), name='vehicle'),
    path('like', views.like, name='like'),
    path('deletemessage', views.deletemessage, name='deletemessage'),
    #path('projectpreview', views.projectpreview, name="projectpreview"),
    path('furniturebytype/<type>', views.FurniturebyType.as_view(), name='furniturebytype'),
    path('searchvehicles', views.VehicleSearch.as_view(), name='searchvehicles'),
    path('vehlike', views.vehlike, name='vehlike'),
    path('comment/reply/', views.reply_page, name="reply")

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

https://{{ domain }}{% url 'website:activate' uidb64=uid token=token %}
{% endautoescape %}

final/templates/base.html
{% load static %}
{% load widget_tweaks %}
{% load mptt_tags %}
{% load custom_tags %} 


<!DOCTYPE html>
<html lang="en">
<head>
  <title>
    {% block title %} 
    {{ value|default_if_none:"Tiny Shelter Archive" }}  
    {% endblock title %}
    
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
<!-- This is ekko-lightbox -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" crossorigin="anonymous">

<!-- End of This is ekko-lightbox -->

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Georama:wght@100;400&display=swap" rel="stylesheet">

  <!--Font awesome -->

  <script src="https://kit.fontawesome.com/468be3d841.js" crossorigin="anonymous"></script>

    <!--End of Font awesome   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
-->


  <link rel="stylesheet"href="{% static 'main.css' %}" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js" crossorigin="anonymous"></script>


  <script src="/static/main.js" crossorigin="anonymous"></script>


<!--This is django-dynamic-formset plugin (see credit in enclosing)-->

  <script src="/static/jquery.formset.js" crossorigin="anonymous"></script>

  <!--End of This is django-dynamic-formset plugin (see credit in enclosing)-->

</head>
<link rel="stylesheet"href="/static/main.css">

<body>

  <div class='wrapper'> 

  








<aside class='side'>



 

  {% if messages %}
  {% for message in messages %}
  
    <div class="message alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  
  {% endfor %}
  {% endif %} 



<button class='hideSidebar'><i class="fa fa-minus-square-o" aria-hidden="true"></i></button>
   
<button class='hideSidebar' style='display:none;'><i class="far fa-plus-square"></i></button>




    <div id='menu'>
      <br>

        <div id='logo'>
        <a style='text-decoration: none;color:rgb(87, 85, 85)' href="{% url 'website:index' %}"><h3 style='font-family:Major Mono Display'>TINY SHELTER ARCHIVE</h3></a>
      </div>
      <div id='smalllogo'>
        <a style='text-decoration: none;color:rgb(87, 85, 85)' href="{% url 'website:index' %}"><h5 style='font-family:Major Mono Display;color:rgb(87, 85, 85;'>TINY SHELTER ARCHIVE</h5></a>
        <hr>
      </div>
      <ul>


        {% if user.is_authenticated %}
     
        
          <li>
                <a href="{% url 'website:garage' user.username %}">Your garage</a>
              </li>
              <li>
                <a href="{% url 'website:profile' user %}">Your profile</a>

              </li>
              <li>
                                <a href="{% url 'website:logout' %}"></span> Logout</a>

              </li>
        {% else %}
        <li>
                <a href="{% url 'website:login' %}">Login</a>
              </li>
        {% endif %}

        <li>
          <button id='search-modal-button'>Search options</button>
        </li>
      </ul>
        </div>

        <br>
      

    <div id='search'>

      <div>
        <h4>VEHICLE SEARCH</h4>
      <form action="{% url 'website:searchvehicles' %}" method="get">
        <select name="type" id="vehicle_type">
          <option value="none">select vehicle type...</option>
          <option value="Van">Van</option>
          <option value="Truck">Truck</option>
          <option value="Automobile">Automobile</option>
          <option value="Trailer">Trailer</option>
          <option value="Boat">Boat</option>
          <option value="Bicycle">Bicycle</option>
          <option value="Immobile">Immobile</option>


        </select>
        <select name="technique" id="build_technique">
          <option value="none">select build technique...</option>
          <option value="aluminum">Aluminum extrusions</option>
          <option value="welding">Welding</option>
          <option value="carpentry">Carpentry</option>
          <option value="fiberglass">Fiberglass</option>
          <option value="CNC">CNC</option>
          <option value="foam">Foam</option>
        </select>
        <br>
  
        <input style='border-radius:0.25em;margin-bottom: 0.25em;' name="q" type="text" placeholder="searches all fields...">
  <br>
        <input type="submit" value="Search">
      </form>
    </div>
  
  <br>
      
      <div>
        <h4>FURNITURE SEARCH</h4>
  
        <select name='type' id="function_selection">
          <option value="none">select furniture function...</option>
          <option value="Kitchen">Kitchen</option>
          <option value="Bathroom">Bathroom</option>
          <option value="Bedroom">Bedroom</option>
          <option value="Garage">Garage</option>
          <option value="Workspace">Workspace</option>
          <option value="Utilities">Utilities</option>
        </select>
  
  
  
    </div>
  
  
  
      </div>


      <div id='search-modal'>

        <div id='search-modal-content'>
          <span class="close1">&times;</span>

        <div>
          <h4>VEHICLE SEARCH</h4>




        <form action="{% url 'website:searchvehicles' %}" method="get">
          <select name="type" id="vehicle_type1">
            <option value="none">select vehicle type...</option>
            <option value="Van">Van</option>
            <option value="Truck">Truck</option>
            <option value="Automobile">Automobile</option>
            <option value="Trailer">Trailer</option>
            <option value="Boat">Boat</option>
            <option value="Bicycle">Bicycle</option>
            <option value="Immobile">Immobile</option>
  
  
          </select>
          <select name="technique" id="build_technique1">
            <option value="none">select build technique...</option>
            <option value="aluminum">Aluminum extrusions</option>
            <option value="welding">Welding</option>
            <option value="carpentry">Carpentry</option>
            <option value="fiberglass">Fiberglass</option>
            <option value="CNC">CNC</option>
            <option value="foam">Foam</option>
          </select>
          <br>
    
          <input style='border-radius:0.25em;margin-bottom: 0.25em;' name="q" type="text" placeholder="searches all fields...">
    <br>
          <input type="submit" value="Search">
        </form>
      </div>
    
    <br>
        
        <div>
          <h4>FURNITURE SEARCH</h4>

          <select name='type' id="function_selection2">
            <option value="none">select furniture function...</option>
            <option value="Kitchen">Kitchen</option>
            <option value="Bathroom">Bathroom</option>
            <option value="Bedroom">Bedroom</option>
            <option value="Garage">Garage</option>
            <option value="Workspace">Workspace</option>
            <option value="Utilities">Utilities</option>
          </select>

          </form>
    
      </div>


    </div>
    
    
        </div>

<br>


    
    <div id='treeview'>



      <h6 id='alt-tree-title' style='font-family:Major Mono Display;color:rgba(0, 0, 0, 0.397);'>Entire collection</h6>
      <h4 id="tree-title"> ENTIRE COLLECTION</h4> 
      <button class='dropdown-tree'><img src="/static/down.png" class="dropdown-img-tree"></button>



    
    <ul class="myUL">
        {% if projects %}
        {% recursetree projects %}
        {% if node.level == 0 %}
    
        {% if not node.is_leaf_node %}
        <li><span class='caret'>{{ node.name }}</span>
      
        {% else %}  
    
        <li>{{ node.name }}
        {% endif %}
    
        {% else %}
          {% if not node.is_leaf_node %}
        <li><span class="caret">{{ node.name }}</span>
          {% else %}
        
          {% if node.tree_linked %}
    
        <li><a class="tree-link" id="{{ node.name }}" href="{% url 'website:vehicle' node.name|slugify %}" >{{ node.name }}

          <span class='tree-like-count'>({{node.like_count}} likes)</span>

        </a>
    
        {% else %}
    
        <li><span class="caret">{{ node.name }}</span>
    
            {% endif %}
    
          {% endif %}
          {% endif %}
    
          {% if not node.is_leaf_node %}
          <ul class="nested">
            {{ children }}
          </ul>
          {% endif %}
        </li>
    
        {% endrecursetree %}
        {% endif %}

      </ul>
    </div>

    <div class='bottomborder'>
      <img src="{% static 'bottomborder.png' %}">
    </div>
    
    </aside>
    
    

  {% block content %} 

  <div class='content'>
    <h3>A repository of tiny shelter builds.</h3>

  <div id='archivetheme'>
  <br>
  <div class='tutorialflex1'>
    <div class='tutorialflex1-child'>
  <h5><i style='margin:20px'>...browse via 3 modes in sidebar</i></h5>
  <h6>(you can minimize sidebar for more screen real estate)</h6>
</div>
<div class='tutorialflex1-child'>
  <h5><i style='margin:20px'>...register to commment, message builders, and submit your own build posts</i></h5>
</div>
<div>
  <h6 class='tutorialflex1-child intro-comment'>Stay tuned for updates. Need to communicate with the site owner? Go public through the 'comments vehicle' or PM me through my profile at profile/vanMan1.</h6>

</div>
</div>
</div>

  
<br>
<h4><i style='margin:20px'>To submit a build,</i></h4>
<ul id='tutorial-uL'>
  <li>Go to your garage and add a vehicle</li>
  <li>Then add 'furniture' to the vehicle</li>
  <li>Each furniture post will have a predominant functionality but you can categorize your build however you choose</li>
      <p class='small'>For example, you could submit 'furniture' submissions for 'cooking area' and 'sleeping quarters' OR 
        for 'memories of me with my van' and 'build progress - timelapse' 
      </p>
</ul>

  </div>

  {% endblock content %} 

      
  </div>
   


 
 




    <script>
      
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });


    </script>







</body>
</html>

final/templates/editprofile.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %} 

{{form_media}}
    <div class="content">
    <h5>Edit profile</h5>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form |crispy }}

        <button type="submit" class="btn btn-primary">Edit profile</button>
    </form>
   

    <span class='border'><em>Message from the website creator: this site will never share your personal email with anyone. The other profile fields will however be displayed on your profile page. Stick around - I do believe we are going to make this site great!</em></span>
{% endblock content %}

final/templates/login.html
{% extends 'base.html' %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="content">
  <h5>Login</h5>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button style='margin-top: 12px;' class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a></p>
  <p class="text-center">Forgot password? <a href="/password_reset">Reset password</a></p>

</div>

{% endblock content %}      

final/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<article class="content">
    <h4 class="text-muted" style='display:inline-block;'>Profile page: {{object.username}}</h4>
    
            {% if user.username == object.username %} 
            
            <a href="{% url 'website:editprofile' user.username %}" role="button" class="edit-delete">Edit profile</a>

            <a href="{% url 'website:deleteaccount' user.username %}" role="button" class="edit-delete">Delete account</a>


            {% endif %}
<div class='profile-flex'>
<div>
 
            <div class="nav-font mx-2 ml-1 mt-1">
                <ul style="list-style-type: None;">
                    <li>
                        <a href="{% url 'website:garage' object.username %}" role="button" class="btn btn-outline-secondary btn-sm">View their projects</a>
                    </li>
                    <li>
                        <a href="{% url 'website:furniturebybuilder' object.username %}" class="btn btn-outline-primary btn-sm">See their furniture</a>
                    </li>


                    {% if user.username != object.username %} 


                    <li>
                        <button class="btn btn-outline-secondary btn-sm" onclick=messenger()>Send them an in-app message</button>
                    </li>
                    
                    {% endif %} 


                </ul>

                <div id="messenger_div" style="display:none">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Send email</button>
                      </form>
                </div>
               
            </div>
            <hr>
           <div>
                <b>Biography:</b>
            </div>
          
            <div style='margin-left:1em;' >
                {{object.profile.bio|safe}}
            </div>
            <hr>
            <div >
                <b>Location: </b><span> {{object.profile.location|default_if_none:"Nothing added here"}}</span>
            </div>
            <div >
               
            </div>
            <div >
                <b>Website: </b><span> {{object.profile.website|default_if_none:"Nothing added here" }}</span>
            </div>
         
    </div>
    <div class='profile-img'>
        <img src="{{object.profile.profile_pic.url}}" alt="{{user}}">
    </div>
</div>

{% if user.username == object.username %} 


<div class="card" >
    <div class="card-header">Messages Recieved<br><span style="font-size: x-small"> Note: messages older than 30 days are deleted</span></div>
    <div class="card-body">
        
        <table class="nav-font table table-bordered table-sm table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Sender</th>
                <th scope="col">Subject</th>
                <th scope="col">Message</th>
                <th scope="col">Time</th>
                <th scope="col">Delete</th>

              </tr>
            </thead>
            <tbody>
            {% for message in recieved_emails %}
              <tr id={{message.id}}>
                <td>{{message.sender}}</td>
                <td>{{message.subject}}</td>
                <td>{{message.message}}</td>
                <td>{{message.sent_at|date:'m-d-Y H:i'}}</td>
                <td>

                    <button type="button" onclick=confirmdelete({{message.id}})>
                            
                        <span id='{{message.id}}-delete'>Delete</span>

                        <button style="display:none" type="button" id='{{message.id}}-confirm' onclick=deletemessage({{message.id}})>Confirm</button>

                    
                    </button>

                </td>

              </tr>
              {% endfor %}

            </tbody>
          </table>
    </div>
    <div class="card"  >
        <div class="card-header">Messages Sent<br><span style="font-size: x-small"> Note: messages older than 30 days are deleted</span></div>
        <div class=" card-body" style="width:100%">
            
            <table class=" nav-font table table-bordered table-sm table-hover ">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Recipient</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Message</th>
                    <th scope="col">Time</th>
                    <th scope="col">Delete</th>
    
                  </tr>
                </thead>
                <tbody>
                {% for message in sent_emails %}
                  <tr id={{message.id}}>
                    <td>{{message.recipient}}</td>
                    <td>{{message.subject}}</td>
                    <td>{{message.message}}</td>
                    <td>{{message.sent_at|date:'m-d-Y H:i'}}</td>
                    <td>
                        
                        <button type="button" onclick=confirmdelete({{message.id}})>
                            
                            <span id='{{message.id}}-delete'>Delete</span>

                            <button style="display:none" type="button" id='{{message.id}}-confirm' onclick=deletemessage({{message.id}})>Confirm</button>

                        
                        </button>
                            
                        
                    </td>
    
    
                  </tr>
                  {% endfor %}
    
                </tbody>
              </table>
        </div>

</div>





</article>
{% endif %} 





{% endblock content %}

final/templates/register.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %} 

    <div class="content">
    <h5>Register</h5>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form |crispy }}
        {{ profile_form |crispy }}

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="login">login</a> instead.</p>
   

    <span class='border'><em>Message from the website creator: this site will never share your personal email with anyone. The other profile fields will however be displayed on your profile page. Stick around - I do believe we are going to make this site great!</em></span>
</div>
{% endblock content %}